#include <algorithm>
#include <any>
#include <cassert>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <functional>
#include <hash.h>
#include <iostream>
#include <memory>
#include <mini_stm.h>
#include <optional>
#include <persistent_array.h>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>
