#include <algorithm>
#include <any>
#include <cassert>
#include <decode_wf_opcode_7_edge_0077.h>
#include <functional>
#include <iostream>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <variant>
